Feature/appcli 32 reduce stateful behaviours
brightsparklabs/appcli pull request #64
Opened 2020-12-03 12:51 UTC by thomas-anderson-bsl

Shifted stateful behaviours into centralised `ConfigurationState` object, so that we know what commands we allow/disallow based on the current state of the configuration repos.

2020-12-08 01:50 UTC, al-jeyapal requested changes

2020-12-08 01:50 UTC, al-jeyapal commented on appcli/configuration/configuration_state.py
> +        if not config_repo.repo_exists():
Lets determine this before creating the `...GitRepository` objects

2020-12-08 01:50 UTC, al-jeyapal commented on appcli/models/cli_context.py
> +            return None
Actually let's throw instead of sending back `None`
Then update the `configuration_state` method above to handle the exception

2020-12-15 19:50 UTC, thomas-anderson-bsl commented on appcli/commands/commands.py
> +class AppcliCommand(Enum):
resolved with 3bd62bb19de59ec545e7b5c6e6c49ff75a7147c9

2020-12-15 20:02 UTC, thomas-anderson-bsl commented on appcli/commands/configure_cli.py
> +            ).apply_configuration_changes(message)
Yes `--force` should be an option, but it should not be on this line. If the 'configure apply' command is run when the generated configuration is dirty, it should block by default, but allow '--force' override. When calling `ConfigurationManager#apply_configuration_changes`, it is already allowed to run the apply, regardless of dirty status, which is why it isn't an argument.

2021-01-20 05:48 UTC, thomas-anderson-bsl commented on appcli/configuration/configuration_state.py
> +        cannot_run = {
Added method to allow getting disallowed commands from a list of allowed commands.

2021-01-20 10:06 UTC, thomas-anderson-bsl commented
@al-jeyapal previous PR comments addressed. Could you please have another look over to make sure it's all good to go?
- Have run `make all`, so linting and tests are fine
- Have tested locally with my own test project and seems to be working as intended

2021-01-20 21:08 UTC, merged